
@default_files = ('master.tex');
$pdf_mode            = 1;
$pdflatex = 'pdflatex -halt-on-error';
$lualatex = 'lualatex -halt-on-error';
@default_files = ('master.tex');
$clean_ext = "lol bbl nav out snm synctex.gz synctex.gz(busy) run.xml tex.bak bbl bcf fdb_latexmk run tdo %R-blx.bib";
$biber = 'biber --validate-datamodel %O %S';

add_cus_dep( 'acn', 'acr', 0, 'makeglossaries' );
add_cus_dep( 'glo', 'gls', 0, 'makeglossaries' );
$clean_ext .= " acr acn alg glo gls glg";
sub makeglossaries {
    my ($base_name, $path) = fileparse( $_[0] );
    pushd $path;
    my $return = system "makeglossaries", $base_name;
    popd;
    return $return;
}
